import { writeFile } from "node:fs/promises";
import { Command } from "commander";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import {
  ensureCcqaDir,
  parseSpecPath,
  getTraceActions,
  getSetupDir,
  readSpecFile,
  saveTestScript,
} from "../store/index.ts";
import { actionsToScript } from "../codegen/actions-to-script.ts";
import type { SetupScript } from "../codegen/actions-to-script.ts";
import { buildCleanupPrompt, buildAutoFixPrompt } from "../prompts/codegen.ts";
import { invokeClaudeStreaming } from "../claude/invoke.ts";
import { parseTestSpec } from "../spec/parser.ts";
import { bundledVitestConfigPath } from "../runtime/bundled-config.ts";
import { spawnVitestCaptured } from "../runtime/spawn-vitest.ts";
import type { TraceAction } from "../types.ts";
import * as log from "./logger.ts";

export const generateCommand = new Command("generate")
  .argument("<feature/spec>", "Spec to generate test for (e.g. tasks/create-and-complete)")
  .description("Generate agent-browser test script from recorded trace actions")
  .option("--max-retries <n>", "Maximum number of auto-fix retries", "3")
  .action(async (specPath: string, opts: { maxRetries: string }) => {
    const { featureName, specName } = parseSpecPath(specPath);
    await runGenerate(featureName, specName, parseInt(opts.maxRetries, 10));
  });

async function runGenerate(featureName: string, specName: string, maxRetries: number): Promise<void> {
  log.header("generate", `${featureName}/${specName}`);

  await ensureCcqaDir();

  const { path: actionsPath, actions } = await getTraceActions(featureName, specName);

  log.meta("trace", actionsPath);
  log.meta("actions", actions.length);

  // Load setup actions if test-spec references setups
  const specContent = await readSpecFile(featureName, specName);
  const spec = parseTestSpec(specContent);
  const setupScripts = await loadSetupScripts(
    spec.setups as Array<{ name: string; params?: Record<string, string> }> | undefined,
  );
  if (setupScripts.length > 0) {
    log.meta("setups", setupScripts.map((s) => s.name).join(", "));
  }
  log.blank();

  const cleanedActions = await cleanupActions(actions);
  if (cleanedActions.length !== actions.length) {
    log.meta("cleaned", cleanedActions.length);
  }

  const script = actionsToScript(cleanedActions, spec.title, setupScripts.length > 0 ? setupScripts : undefined);
  const scriptPath = await saveTestScript(featureName, specName, script);
  log.meta("saved", scriptPath);
  log.blank();

  let { exitCode, output, currentScript } = await runVitest(scriptPath);
  if (exitCode === 0) {
    log.hint(`run 'ccqa run ${featureName}/${specName}' to execute the test`);
    return;
  }

  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    log.info(`auto-fix attempt ${attempt}/${maxRetries}...`);
    log.blank();

    const fixed = await autoFixWithLLM(currentScript, output);
    if (!fixed) {
      log.warn("could not determine fix from failure log");
      break;
    }

    await writeFile(scriptPath, fixed, "utf-8");
    log.meta("saved", scriptPath);
    log.blank();

    ({ exitCode, output, currentScript } = await runVitest(scriptPath));
    if (exitCode === 0) {
      log.hint(`run 'ccqa run ${featureName}/${specName}' to execute the test`);
      return;
    }
  }

  log.warn("auto-fix exhausted — test still failing");
  process.exit(1);
}

/**
 * Load setup test scripts, extract test body, and replace {{placeholders}} with params values.
 */
async function loadSetupScripts(
  setups?: Array<{ name: string; params?: Record<string, string> }>,
): Promise<SetupScript[]> {
  if (!setups?.length) return [];

  const result: SetupScript[] = [];
  for (const ref of setups) {
    const scriptPath = join(getSetupDir(ref.name), "test.spec.ts");
    const script = await readFile(scriptPath, "utf-8").catch(() => {
      throw new Error(`Setup test script not found: ${scriptPath}. Run \`ccqa generate-setup ${ref.name}\` first.`);
    });
    const body = extractTestBody(script);
    const resolved = replacePlaceholders(body, ref.params ?? {});
    result.push({ name: ref.name, body: resolved });
  }
  return result;
}

/**
 * Extract the test body (statements inside the test callback) from a setup
 * test script.
 *
 * Locates the first arrow callback (`=> {`) after a top-level `test(` call
 * and returns the text between the matching `{` and `}`. Handles both
 * single-line and multi-line `test(...)` formatting (the latter is what
 * prettier produces).
 *
 * Brace tracking is naive (string/regex/comment literals are not parsed
 * specially), but setup test scripts are themselves generated by ccqa and
 * follow a fixed shape, so this is sufficient in practice.
 */
function extractTestBody(script: string): string {
  const testCallMatch = /\btest\s*\(/.exec(script);
  if (!testCallMatch) return "";
  const arrowIdx = script.indexOf("=> {", testCallMatch.index);
  if (arrowIdx === -1) return "";
  const bodyStart = arrowIdx + "=> {".length;
  let depth = 1;
  let i = bodyStart;
  for (; i < script.length; i++) {
    const ch = script[i]!;
    if (ch === "{") depth++;
    else if (ch === "}") {
      depth--;
      if (depth === 0) break;
    }
  }
  if (depth !== 0) return "";
  return script.slice(bodyStart, i).replace(/^\n/, "").replace(/\n\s*$/, "");
}

function replacePlaceholders(body: string, params: Record<string, string>): string {
  let result = body;
  for (const [key, value] of Object.entries(params)) {
    result = result.replaceAll(`{{${key}}}`, value);
  }
  return result;
}

// --- Auto-fix ---

interface SleepInsert { line: number; seconds: number; reason: string }
interface SleepIncrease { line: number; increase_to: number; reason: string }
type AutoFixAction = SleepInsert | SleepIncrease;

async function autoFixWithLLM(script: string, failureLog: string): Promise<string | null> {
  try {
    const prompt = buildAutoFixPrompt(script, failureLog);
    const { result, isError } = await invokeClaudeStreaming(
      { prompt, disableBuiltinTools: true, maxTurns: 1 },
      () => {},
    );
    if (isError || !result) return null;

    const json = result.trim().replace(/^```(?:json)?\n?([\s\S]*?)\n?```$/, "$1").trim();
    const fixes = JSON.parse(json) as AutoFixAction[];
    if (!Array.isArray(fixes) || fixes.length === 0) return null;

    return applySleepFixes(script, fixes);
  } catch {
    return null;
  }
}

function applySleepFixes(script: string, fixes: AutoFixAction[]): string {
  const lines = script.split("\n");

  for (const fix of fixes) {
    if ("increase_to" in fix) {
      const idx = fix.line - 1;
      if (idx >= 0 && idx < lines.length) {
        lines[idx] = lines[idx]!.replace(
          /spawnSync\("sleep",\s*\["\d+"\]/,
          `spawnSync("sleep", ["${fix.increase_to}"]`,
        );
      }
    }
  }

  const inserts = fixes
    .filter((f): f is SleepInsert => "seconds" in f && !("increase_to" in f))
    .sort((a, b) => b.line - a.line);

  for (const fix of inserts) {
    const idx = fix.line - 1;
    if (idx >= 0 && idx <= lines.length) {
      lines.splice(idx, 0, `  spawnSync("sleep", ["${fix.seconds}"], { stdio: "inherit" });`);
    }
  }

  return lines.join("\n");
}

async function runVitest(scriptPath: string): Promise<{ exitCode: number; output: string; currentScript: string }> {
  const { exitCode, stdout, stderr } = await spawnVitestCaptured([
    "run",
    "--config",
    bundledVitestConfigPath(),
    scriptPath,
  ]);
  const currentScript = await readFile(scriptPath, "utf8");

  process.stdout.write(stdout);
  if (stderr) process.stderr.write(stderr);
  return { exitCode, output: stdout + stderr, currentScript };
}

async function cleanupActions(actions: TraceAction[]): Promise<TraceAction[]> {
  try {
    const prompt = buildCleanupPrompt(actions);
    const { result, isError } = await invokeClaudeStreaming(
      { prompt, disableBuiltinTools: true, maxTurns: 1 },
      () => {},
    );
    if (isError || !result) return actions;
    const json = result.trim().replace(/^```(?:json)?\n?([\s\S]*?)\n?```$/, "$1").trim();
    const parsed = JSON.parse(json) as TraceAction[];
    if (Array.isArray(parsed) && parsed.length > 0) return parsed;
  } catch {
    // Fall through
  }
  return actions;
}
